import { ReactNode } from 'react';

import { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Toaster } from 'sonner';

import { cn } from '@/lib/utils';

import Providers from './Providers';
import Viewport from './Viewport';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Crimplex',
  description: 'Generated by create next app',
};

const Document = ({ children }: { children: ReactNode }) => {
  return (
    <html lang="en" className="h-full" suppressHydrationWarning>
      <body
        className={cn('relative h-full font-sans antialiased', inter.className)}
        suppressHydrationWarning
      >
        <Providers>
          <Viewport>
            <Toaster richColors position="top-center" duration={3000} />
            {children}
          </Viewport>
        </Providers>
      </body>
    </html>
  );
};

export default Document;
